### ISSUE TITLE
 As a member, I can click on a slack channel and scroll through a list of all messages in that channel.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-mapache-search#12]
# User Story:

As a member, I can click on a slack channel and scroll through a list of all messages in that channel.

# Acceptance Criteria

- [x] There is a front end route `/channels/:channel` (where `:channel` is the channel name) that is available only to members/admins.  Initially, this route can be accessed only by typing it into the URL bar (linking to it comes later).  This route displays, initially, a page that just has the title of the channel.  (NOTE: Staff might do just this step ourselves as scaffolding for the student epic.) 
- [x] The page `/channels/:channel` includes a view of a table for messages.  Initially; these might be fake messages hard coded in the component. The data shown for now can simply be the raw data from the message (see "Sample Message Data", below), namely:  `type`, `subtype`, `ts`, `user`, `text` (making that display more user friendly, i.e. replacing userid with the human facing userid, is a separate story).
- [x] The data on the page `channels/:channel` is real data from the back end, not fake data.

# Implementation TODOS

Front End:

- [x] Add a page under `/javascript/src/main/components` for `ChannelMessages`
- [x] Add an `AuthorizedRoute` in  `App.js` at  `/channels/:channel` that goes to the ChannelMessages page.
- [x] The page should link to a `MessageTable` component (added under `/javascript/src/main/components`) that uses `BootstrapTable` to display a list of messages,  initially fake hard coded messages.
- [x] Once the backend routes are in place, instead of fake hard coded messages, display the real messages.  This involves using `useSWR` to get the data from the back end.

Back End:

- [x] Add a `MessagesRepository` class that corresponds to the `messages` collection in the MongoDB database.  This should have a `findByChannel` method that takes a channel and returns a collection of all messages for that channel. 
- [x] Add a `MessageDocument` class that corresponds to the document (the JSON object) for each message.
- [x] In the `ChannelsController` class add a route `/api/members/channel/:channel/messages` that retrieves a list of messages from the specified channel. 

Testing:
- [x] Front end test coverage should be as close to 100% as possible (from `javascript` subdirectory, use `npm run coverage`)
- [x] Back end test coverage should be as close to 100% as possible (from top dir, use `mvn test jacoco:report -Dskip.npm`)

# Sample Message data

```json
{
    "_id": {
        "$oid": "5fb419ec25aaabcbb459cdc0"
    },
    "type": "message",
    "subtype": "channel_join",
    "ts": "1594143066.000200",
    "user": "U017218J9B3",
    "text": "<@U017218J9B3> has joined the channel",
    "channel": "section-6pm"
}
```

**Comment by shouc** [comment]
to curl API: 
```
curl -H "Authorization: [YOUR TOKEN]" http://localhost:3000/api/members/channel/articles-react/messages | json_pp
```

sample data:
```json
   [{
      "channel" : "articles-react",
      "subtype" : null,
      "text" : "<https://blog.logrocket.com/a-low-friction-way-to-do-tdd-with-react/|https://blog.logrocket.com/a-low-friction-way-to-do-tdd-with-react/>",
      "ts" : "1597724354.000200",
      "type" : "message",
      "user" : "U017218J9B3",
      "user_profile" : {
         "display_name" : "Phill Conrad (he/him/his)",
         "email" : null,
         "name" : "phtcon",
         "real_name" : "Phillip Conrad"
      }
   }]

```
Issue 18 should be directly using the `user_profile` field
