### ISSUE TITLE
User can add personal Google API Search Token to their account

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-mapache-search#135]
# User Story

As a user I can add a custom google search api token to my account, so that I can enable searching from within the mapache search app for up to 100 searches per user per day.

# Discussion

A team worked on this during F20, but did not finish.  There is an unmerged PR that has some work in it that you may use as a guide, or you can start fresh, as you see fit.

* Previous Issue: https://github.com/ucsb-cs156-w21/proj-mapache-search/issues/37
* Previous PR: https://github.com/ucsb-cs156-w21/proj-mapache-search/pull/81

# Acceptance Criteria

- [x] Each user will be able to submit up to 100 searches per day
- [x] Each user will be able to associate a custom google search api token with their unique account

# Implementation Todos

Front end:
- [x] Implement a field to input a custom google search api token
- [x] Display error message for invalid token

Back end:
- [x] Create variable/object to store unique custom google search api tokens with each account
- [x] Modify AppUser Entity in order to account for extra api token field
- [x] Add route to story token in AppUser database
- [x] Implement tests and error message for invalid token

**Comment by jasunchen** [comment]
6pm-4-CustomGoogleAPI
