### ISSUE TITLE
Histogram of Messages for a user over time

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-mapache-search#136]
# Epic

This ticket is a sub-ticket of #146 created by phtcon

# User Story

As a member/admin I can see user-specific level of activity histogram (by week) so that I can see when certain people are online and their participation in the course

# Discussion

* A team worked on this as Issue #30 in F20 but did not complete the issue.
* A PR with the progress they made can be found here: #87 
* The S21 team can build on what the W21 / F20 team did, or start over, just using the previous work for reference.

# Acceptance Criteria

- [ ] Ability to select a user and view their activity histogram
- [ ] Activity histogram has y axis of time, x axis of message count 
- [ ] Consistent scale of message count for all users
- [ ] Correct number of messages displayed per user (there are currently duplicates, these should be eliminated - this also needs to happen in all other message analytics pages so feel free to collaborate with ppl working on those pages)

# Implementation Todos

Front end:

- [ ] Create React Component that can be added to a user's profile to display the histogram
- [ ] Use backend message data to populate the histogram, specific to each user (dependent on unique user id)
- [ ] Determine a consistent scale to uniformly use across the histograms

Back end:

- [x] Connect to the database and retrieve the message count, separated and sorted by day

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by avatarmiko** [comment]
branch: 6pm-2-messages-histogram
