### ISSUE TITLE
New database table `Searches`

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-s21/proj-mapache-search#156]
Add a new entity and repository object called `Search` and `SearchRepository`

Fields:
* id (normal database table id)
* searchTerm (string, the search that was done)
* count (number of times this search has been performed)

For this story, the only thing necessary is to add this database table.  There will be other stories that depend on this being in place.

**Comment by phtcon** [comment]
@jc9907 Moved this back to In progress.  It can't be in the Done column if there is no linked pull request.
