### ISSUE TITLE
Replace weird Slack internal userids with meaningful userids.

### ISSUE THREAD

**Issue by nicholasbrown1** [ucsb-cs156-s21/proj-mapache-search#18]
# User Story

As a user I can see names instead of just a Slack ids so that I can tell who sent the message.

# Acceptance Criteria

- [x] Names are displayed instead of Slack ids.

# Implementation Todos

Front end:

- [x] Names are displayed next to the messages rather than slack ids. 

Back end:

- [x] Convert the slack id data to a user name.

Testing:

- [x] Front end tests pass and there is as close to 100% coverage as possible
- [x] Back end tests pass and there is as close to 100% coverage as possible
...

**Comment by shouc** [comment]
backend is done and this issue should be considered as part of the issue 12
