### ISSUE TITLE
Show correct user status in Admin table

### ISSUE THREAD

**Issue by andrewhlu** [ucsb-cs156-s21/proj-mapache-search#216]
# User Story

As an admin, I can see a user's current role in the admin table so that I can know whether a user is a guest or a member.

# Acceptance Criteria

In the users table in the admin panel:

- [x] if a user is a member (meaning they are a user in the Slack users list), they are listed with the "Member" role.
- [x] if a user is a guest (meaning they are NOT a user in the Slack users list), they are listed with the "Guest" role.

Currently, all users (i.e. non-admins) show up with the "User" role, which isn't helpful.

# Implementation Todos

Currently, the page is architected in the following manner:
* Get a list of all users from the `/users` endpoint
* Get a list of all admins from the `/admins` endpoint
* Use both of these to display the table

My thought on how we should make this happen: integrate the admins endpoint into the users endpoint, and return an extra column in the JSON that returns the correct role. 

Front end:

- [x] Fix the table rendering code to render the "Role" column correctly

Back end:

- [ ] Add a "Role" key to each user in the `/users` JSON output
- [ ] Possibly look into removing the `/admins` endpoint if it isn't being used anywhere else

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by nicomwong** [comment]
I see that `/users` and `/admins` return information from the `appUserRepository` and `adminRepository`, respectively. What is the current differentiation between a "user" and an "admin"; what is the person an admin on? Also, where can I modify the information that `appUserRepository` holds (in order to add a new role field)?
