### ISSUE TITLE
/mapache search google string

### ISSUE THREAD

**Issue by XuperBryan** [ucsb-cs156-s21/proj-mapache-search#29]
# User Story

As a user within the slack channel, I can search for topics via Google's custom search engine within the slack channel so that when the user wants more information regarding a certain topic, the slack bot will return the top searches obtained from Google. Ex: if a conversation regarding a certain java function was done on slack, the slack bot will return the top searches regarding that algorithm on the slack chat window.

# Acceptance Criteria

- [x] Webpage URL's of the top searches are returned when the function is called
- [x] The results of the search should be sent back to the corresponding channel where the function was called

# Implementation Todos

Front end:

- [x] Display the top google searches within the slack channel

Back end:

- [x]  Include a google search engine API within the slack channel backend such that the keyword being searched can be obtained from the function call to search on google
- [x] Adding the top results from a certain search to a list such that it can be easily outputted onto the slack channel
- [x] Format the list such that it has the clickable URL links and have some keywords corresponding to the link which informs what the link is about

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

**Comment by Fluellen-Arman** [comment]
Google search seems to be functioning properly and has full code coverage.

**Comment by andrewhlu** [comment]
Issue is complete, though we may want to make the results look nicer in the future.
